### ISSUE TITLE
Could we move the bullet (or other package) src directory outside the build directory?

### ISSUE THREAD

**Issue by mpowelson** [ros-industrial-consortium/tesseract_ext#6]
Would it be extraordinarily bad idea to make add another directory to the workspace called ext or something and use that for the CMake ExternalProject SOURCE_DIR? That way when someone removes the build directory, they would not have to be downloaded again. We could perhaps even do something like copy the results into some cache directory somewhere and then before calling external project, check and see if it is in there.

**Comment by gavanderhoorn** [comment]
Can you clarify what is making you suggest/ask this? Is the download slow? Is the build slow?

Both of these could potentially be addressed without writing files outside of the project's build dir -- which would indeed be going against <del>bad</del> *best* practices.

**Comment by mpowelson** [comment]
Well building bullet has always been slow. But now that we are downloading bullet at compile time rather than as a submodule, if you delete the build directory using catkin clean for instance, then it has to download it again. This could be problematic for a couple of reasons, but speed is certainly one of them.

**Comment by gavanderhoorn** [comment]
Have you installed and enabled `ccache`?

**Comment by mpowelson** [comment]
Not currently. I know that would speed up compilation, but would that prevent having to re-download it? Doesn't it get downloaded before that?

**Comment by gavanderhoorn** [comment]
Caching the build was specifically a reply to:

> Well building bullet has always been slow.

I would recommend you install `ccache` as it really helps with rebuilds (going from minutes to seconds).

For caching downloads you could look into something like a transparent proxy (Squid would be one option).

Unfortunately building things from source means you lose those as soon as you remove the build dir, or at least, if you then don't also install them.

A workaround that could potentially help is to use workspace overlaying where you build Bullet (and perhaps some of the other from-source builds in `tesseract_ext`) in an underlay and then the rest of Tesseract in the main workspace that extends the underlay.

Cleaning out the `build` space of your main workspace would then not touch anything in the underlay.

**Comment by Levi-Armstrong** [comment]
Also to prevent from downloading the source on clean rebuild, you may be able to change the source directory `SOURCE_DIR        ${CMAKE_BINARY_DIR}/../tesseract_ext/Eigen3-src` to `SOURCE_DIR        ${CMAKE_SOURCE_DIR}/Eigen3-src`. I have not tested this but it should work.

**Comment by mpowelson** [comment]
Practically speaking, this is what we are doing. We are using extended workspaces for these packages that hopefully never change and doing things like having a separate one for built in debug. Anyway, it sounds like to my question of whether or not it was an extraordinarily bad idea, the answer is yes.

**Comment by gavanderhoorn** [comment]
Well I'm not claiming it's an *extraordinarily* bad idea. Just that it's typically not considered a very good one to write things outside the build folder from a build script. It would seem to violate the principle-of-least-surprise.

**Comment by gavanderhoorn** [comment]
> Practically speaking, this is what we are doing. We are using extended workspaces for these packages that hopefully never change and doing things like having a separate one for built in debug

But seeing as you posted this issue, I'm guessing it isn't working for?

**Comment by mpowelson** [comment]
It does work as long as I have set that up. But if someone hasn't set that up for whatever reason, it could be a pain to work with. A lot of our instructions just say to run wstool and go - which obviously does work. However, speaking of surprising it might surprise someone that doesn't know what is going on that they need internet access to build trajopt/tesseract even after cloning and running rosdep. I don't know that we have run into it yet, but I imagine it is only a matter of time.

My particular issue was that I was (seemingly) having trouble getting Colcon to overlay properly so I just put everything in one workspace. That's what motivated me to see if we could move the source directory was possible. I saw that it was and wondered if that was a bad idea. Hence the issue.

**Comment by mpowelson** [comment]
I should also add, I am not proposing we spend a lot of time worrying about it. I was just wondering if that was an option.

**Comment by gavanderhoorn** [comment]
> A lot of our instructions just say to run wstool and go - which obviously does work.

maybe we should update those, especially seeing as tesseract is the first project that builds so many dependencies from source. In such cases it may actually make more sense to *first* deal with dependencies (potentially in an underlay) and only *then* start setting up the main Colcon/Catkin workspace.

It could certainly help avoid the frustrations you seem to have run into.

> However, speaking of surprising it might surprise someone that doesn't know what is going on that they need internet access to build trajopt/tesseract even after cloning and running rosdep.

That's certainly not something people might expect and would be remedied by splitting the installation instructions as I suggest above, together with a proper explanation of why this is needed.

> My particular issue was that I was (seemingly) having trouble getting Colcon to overlay properly so I just put everything in one workspace.

Pedantic, but: that would seem to be something to figure out at the Colcon side. Putting everything in a single workspace (or storing build artefacts outside the `build` folder) is at best a workaround.

I realise getting to the bottom of things is not always possible (due to time/effort constraints), but it would be great if we could avoid then making such workarounds SOP.

> I should also add, I am not proposing we spend a lot of time worrying about it. I was just wondering if that was an option.

It's good to discuss these aspects of tesseract as it clearly shows that building dependencies from source is something which can quickly get unwieldy. I'm not saying here it's wrong -- as there are requirements that make it necessary -- but there are definite advantages to packaging software properly and the issues you are running into are an example of this.

---

Summarising: perhaps the underlay/overlay workflow should be documented. This would require having separate `.rosinstall` files and a clear explanation of why this is necessary/beneficial.

**Comment by gavanderhoorn** [comment]
Personally I would perhaps even recommend not to use `git` submodules, but that's another discussion.
